resources:
  - method: POST
    path: "/purchase"
    rules:
      limits:
        - window_seconds: 10
          limit: 10
        - window_seconds: 60
          limit: 50
          algorithm: sliding_window_counter
        - window_seconds: 86400
          limit: 1000
